### PR TITLE
[WIP] refactor: shift constants

### PR DESCRIPTION
**Pull request by apgapg**
Signed-off-by: Ayush P Gupta <ayushpguptaapg@gmail.com>

This PR aims at shifting different constants to `constants` dart file.

Although constants must not have any framwork dependency but this PR add `material` import in `constants.dart`. If this is not a concern then we can proceed to shift other constants too other wise we can discard this approach.

Fixes #(issue)

## Type of change

Please tick the relevant option by putting an X inside the bracket

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] All current GitHub actions pass
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) document

### CODE REVIEW

**Comment by apgapg** [comment]
Also if possible can we add WIP github app to this repository so as to prevent merge option to PR with WIP tags

**Comment by SincerelyFaust** [comment]
You can create a draft pull request in that case

**Comment by apgapg** [comment]
Hi @SincerelyFaust should we continue with the approach i mentioned in the PR description?

**Comment by SincerelyFaust** [comment]
> Hi @SincerelyFaust should we continue with the approach i mentioned in the PR description?

Considering these constants are used only in one file and are not shared between multiple files, I think we should leave it how it is.
The rest of the code in the constants.dart file are the dummy lists which will be removed in future.
Thank you for this PR regardless! :)

**Comment by apgapg** [comment]
Yes i felt the same. 
I am closing this scope then

**Pull request closed without merging**
